<a href="https://colab.research.google.com/github/LeeGitaek/2020_AI_Class/blob/master/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Logistic Regression

H(x) = sigmoid 

cost(w) = cross - entropy

weight update via Gradient Descent

데이터 로드 - > 모델 학습 -> 데이터평가 / 결과 예측 

In [1]:
import torch 
#최적화 알고리즘 : SGD
import torch.optim as optim;
# for reproducibility
torch.manual_seed(1);

x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_data)
print(x_train)

print(x_train.shape)
print(y_train.shape)




[[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
torch.Size([6, 2])
torch.Size([6, 1])


모델 학습


In [4]:
w = torch.zeros((2,1),requires_grad=True)
b = torch.zeros(1,requires_grad=True)

optimizer = optim.SGD([w,b],lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
    hypothesis = torch.sigmoid(x_train.matmul(w)+b)

    cost = -(y_train * torch.log(hypothesis) + (1-y_train) * torch.log(1-hypothesis)).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('epoch {:4d} / {} cost : {:.6f}'.format(
            epoch,nb_epochs,cost.item()
        ))

epoch    0 / 1000 cost : 0.693147
epoch  100 / 1000 cost : 0.134722
epoch  200 / 1000 cost : 0.080643
epoch  300 / 1000 cost : 0.057900
epoch  400 / 1000 cost : 0.045300
epoch  500 / 1000 cost : 0.037261
epoch  600 / 1000 cost : 0.031673
epoch  700 / 1000 cost : 0.027556
epoch  800 / 1000 cost : 0.024394
epoch  900 / 1000 cost : 0.021888
epoch 1000 / 1000 cost : 0.019852


데이터 평가 


In [6]:
hypothesis = torch.sigmoid(x_train.matmul(w)+b)
#print(hypothesis[:5])

prediction = hypothesis  >= torch.FloatTensor([0.5])
#print(prediction[:5])

#print(y_train[:5])

correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('the model has an accuracy of {:2.2f}% for the training set.'.format(accuracy*100))


tensor([[True],
        [True],
        [True],
        [True],
        [True]])
the model has an accuracy of 100.00% for the training set.


In [7]:
xx = [100,5]
xx = torch.FloatTensor(xx)
hypothesis = torch.sigmoid(xx.matmul(w)+b)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([True])
